services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
    command: ["redis-server"]

  postgres:
    container_name: subscriptions_db
    image: postgres:13.3
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: user
      POSTGRES_DB: subscriptions
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    container_name: subscriptions_api
    build:
      context: .
      dockerfile: "./pkg/go/api/Dockerfile"
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - .:/usr/src/build
    ports:
      - "8000:8000"

  notification:
    container_name: subscriptions_notifications
    build:
      context: .
      dockerfile: "./pkg/go/notification/Dockerfile"
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - .:/usr/src/build

  user:
    container_name: subscriptions_user
    build:
      context: .
      dockerfile: "./pkg/go/user/Dockerfile"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/usr/src/build

  weather:
    container_name: subscriptions_weather
    build:
      context: .
      dockerfile: "./pkg/go/weather/Dockerfile"
    volumes:
      - .:/usr/src/build

volumes:
  pgdata:
