// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: weather/v1/weather.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WeatherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherRequest) Reset() {
	*x = WeatherRequest{}
	mi := &file_weather_v1_weather_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherRequest) ProtoMessage() {}

func (x *WeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weather_v1_weather_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherRequest.ProtoReflect.Descriptor instead.
func (*WeatherRequest) Descriptor() ([]byte, []int) {
	return file_weather_v1_weather_proto_rawDescGZIP(), []int{0}
}

func (x *WeatherRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type WeatherReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Temperature   float32                `protobuf:"fixed32,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity      float32                `protobuf:"fixed32,2,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherReply) Reset() {
	*x = WeatherReply{}
	mi := &file_weather_v1_weather_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherReply) ProtoMessage() {}

func (x *WeatherReply) ProtoReflect() protoreflect.Message {
	mi := &file_weather_v1_weather_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherReply.ProtoReflect.Descriptor instead.
func (*WeatherReply) Descriptor() ([]byte, []int) {
	return file_weather_v1_weather_proto_rawDescGZIP(), []int{1}
}

func (x *WeatherReply) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *WeatherReply) GetHumidity() float32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *WeatherReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_weather_v1_weather_proto protoreflect.FileDescriptor

const file_weather_v1_weather_proto_rawDesc = "" +
	"\n" +
	"\x18weather/v1/weather.proto\"$\n" +
	"\x0eWeatherRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\"n\n" +
	"\fWeatherReply\x12 \n" +
	"\vtemperature\x18\x01 \x01(\x02R\vtemperature\x12\x1a\n" +
	"\bhumidity\x18\x02 \x01(\x02R\bhumidity\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription2@\n" +
	"\x0eWeatherService\x12.\n" +
	"\n" +
	"GetWeather\x12\x0f.WeatherRequest\x1a\r.WeatherReply\"\x00BBZ@github.com/Rabiann/weather-mailer/pkg/go/user/v1/internal/protosb\x06proto3"

var (
	file_weather_v1_weather_proto_rawDescOnce sync.Once
	file_weather_v1_weather_proto_rawDescData []byte
)

func file_weather_v1_weather_proto_rawDescGZIP() []byte {
	file_weather_v1_weather_proto_rawDescOnce.Do(func() {
		file_weather_v1_weather_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_weather_v1_weather_proto_rawDesc), len(file_weather_v1_weather_proto_rawDesc)))
	})
	return file_weather_v1_weather_proto_rawDescData
}

var file_weather_v1_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_weather_v1_weather_proto_goTypes = []any{
	(*WeatherRequest)(nil), // 0: WeatherRequest
	(*WeatherReply)(nil),   // 1: WeatherReply
}
var file_weather_v1_weather_proto_depIdxs = []int32{
	0, // 0: WeatherService.GetWeather:input_type -> WeatherRequest
	1, // 1: WeatherService.GetWeather:output_type -> WeatherReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_weather_v1_weather_proto_init() }
func file_weather_v1_weather_proto_init() {
	if File_weather_v1_weather_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_weather_v1_weather_proto_rawDesc), len(file_weather_v1_weather_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_weather_v1_weather_proto_goTypes,
		DependencyIndexes: file_weather_v1_weather_proto_depIdxs,
		MessageInfos:      file_weather_v1_weather_proto_msgTypes,
	}.Build()
	File_weather_v1_weather_proto = out.File
	file_weather_v1_weather_proto_goTypes = nil
	file_weather_v1_weather_proto_depIdxs = nil
}
