// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: v1/user.proto

package protos

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTokenRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId int32                  `protobuf:"varint,1,opt,name=subscriptionId,proto3" json:"subscriptionId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTokenRequest) Reset() {
	*x = CreateTokenRequest{}
	mi := &file_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenRequest) ProtoMessage() {}

func (x *CreateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateTokenRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTokenRequest) GetSubscriptionId() int32 {
	if x != nil {
		return x.SubscriptionId
	}
	return 0
}

type TokenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenReply) Reset() {
	*x = TokenReply{}
	mi := &file_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenReply) ProtoMessage() {}

func (x *TokenReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenReply.ProtoReflect.Descriptor instead.
func (*TokenReply) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *TokenReply) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetSubOfToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubOfToken) Reset() {
	*x = GetSubOfToken{}
	mi := &file_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubOfToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubOfToken) ProtoMessage() {}

func (x *GetSubOfToken) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubOfToken.ProtoReflect.Descriptor instead.
func (*GetSubOfToken) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetSubOfToken) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type SubReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sub           int32                  `protobuf:"varint,1,opt,name=sub,proto3" json:"sub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubReply) Reset() {
	*x = SubReply{}
	mi := &file_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubReply) ProtoMessage() {}

func (x *SubReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubReply.ProtoReflect.Descriptor instead.
func (*SubReply) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *SubReply) GetSub() int32 {
	if x != nil {
		return x.Sub
	}
	return 0
}

type UseTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseTokenRequest) Reset() {
	*x = UseTokenRequest{}
	mi := &file_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseTokenRequest) ProtoMessage() {}

func (x *UseTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseTokenRequest.ProtoReflect.Descriptor instead.
func (*UseTokenRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *UseTokenRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type SubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Period        string                 `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionRequest) Reset() {
	*x = SubscriptionRequest{}
	mi := &file_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionRequest) ProtoMessage() {}

func (x *SubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *SubscriptionRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SubscriptionRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *SubscriptionRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type SubscriptionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionReply) Reset() {
	*x = SubscriptionReply{}
	mi := &file_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionReply) ProtoMessage() {}

func (x *SubscriptionReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionReply.ProtoReflect.Descriptor instead.
func (*SubscriptionReply) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *SubscriptionReply) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ActivateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateRequest) Reset() {
	*x = ActivateRequest{}
	mi := &file_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateRequest) ProtoMessage() {}

func (x *ActivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateRequest.ProtoReflect.Descriptor instead.
func (*ActivateRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *ActivateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ActivateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateReply) Reset() {
	*x = ActivateReply{}
	mi := &file_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateReply) ProtoMessage() {}

func (x *ActivateReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateReply.ProtoReflect.Descriptor instead.
func (*ActivateReply) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *ActivateReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PeriodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeriodRequest) Reset() {
	*x = PeriodRequest{}
	mi := &file_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodRequest) ProtoMessage() {}

func (x *PeriodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodRequest.ProtoReflect.Descriptor instead.
func (*PeriodRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *PeriodRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type ActiveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*ActiveSubscriber    `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveReply) Reset() {
	*x = ActiveReply{}
	mi := &file_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveReply) ProtoMessage() {}

func (x *ActiveReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveReply.ProtoReflect.Descriptor instead.
func (*ActiveReply) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *ActiveReply) GetSubscriptions() []*ActiveSubscriber {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type ActiveSubscriber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Period        string                 `protobuf:"bytes,4,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveSubscriber) Reset() {
	*x = ActiveSubscriber{}
	mi := &file_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveSubscriber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveSubscriber) ProtoMessage() {}

func (x *ActiveSubscriber) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveSubscriber.ProtoReflect.Descriptor instead.
func (*ActiveSubscriber) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *ActiveSubscriber) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActiveSubscriber) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ActiveSubscriber) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ActiveSubscriber) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Subscriber    *SubscriptionRequest   `protobuf:"bytes,2,opt,name=subscriber,proto3" json:"subscriber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRequest) GetSubscriber() *SubscriptionRequest {
	if x != nil {
		return x.Subscriber
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_v1_user_proto protoreflect.FileDescriptor

const file_v1_user_proto_rawDesc = "" +
	"\n" +
	"\rv1/user.proto\x1a\x1bgoogle/protobuf/empty.proto\"<\n" +
	"\x12CreateTokenRequest\x12&\n" +
	"\x0esubscriptionId\x18\x01 \x01(\x05R\x0esubscriptionId\" \n" +
	"\n" +
	"TokenReply\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"#\n" +
	"\rGetSubOfToken\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x1c\n" +
	"\bSubReply\x12\x10\n" +
	"\x03sub\x18\x01 \x01(\x05R\x03sub\"%\n" +
	"\x0fUseTokenRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"W\n" +
	"\x13SubscriptionRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x16\n" +
	"\x06period\x18\x03 \x01(\tR\x06period\"#\n" +
	"\x11SubscriptionReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"!\n" +
	"\x0fActivateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x1f\n" +
	"\rActivateReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\rPeriodRequest\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\"F\n" +
	"\vActiveReply\x127\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x11.ActiveSubscriberR\rsubscriptions\"d\n" +
	"\x10ActiveSubscriber\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x16\n" +
	"\x06period\x18\x04 \x01(\tR\x06period\"U\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x124\n" +
	"\n" +
	"subscriber\x18\x02 \x01(\v2\x14.SubscriptionRequestR\n" +
	"subscriber\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id2\xe4\x03\n" +
	"\vUserService\x12=\n" +
	"\x0fAddSubscription\x12\x14.SubscriptionRequest\x1a\x12.SubscriptionReply\"\x00\x12:\n" +
	"\x14ActivateSubscription\x12\x10.ActivateRequest\x1a\x0e.ActivateReply\"\x00\x128\n" +
	"\x16GetActiveSubscriptions\x12\x0e.PeriodRequest\x1a\f.ActiveReply\"\x00\x12>\n" +
	"\x12UpdateSubscription\x12\x0e.UpdateRequest\x1a\x16.google.protobuf.Empty\"\x00\x12>\n" +
	"\x12DeleteSubscription\x12\x0e.DeleteRequest\x1a\x16.google.protobuf.Empty\"\x00\x121\n" +
	"\vCreateToken\x12\x13.CreateTokenRequest\x1a\v.TokenReply\"\x00\x125\n" +
	"\x16GetSubscriptionOfToken\x12\x0e.GetSubOfToken\x1a\t.SubReply\"\x00\x126\n" +
	"\bUseToken\x12\x10.UseTokenRequest\x1a\x16.google.protobuf.Empty\"\x00BBZ@github.com/Rabiann/weather-mailer/pkg/go/user/v1/internal/protosb\x06proto3"

var (
	file_v1_user_proto_rawDescOnce sync.Once
	file_v1_user_proto_rawDescData []byte
)

func file_v1_user_proto_rawDescGZIP() []byte {
	file_v1_user_proto_rawDescOnce.Do(func() {
		file_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_user_proto_rawDesc), len(file_v1_user_proto_rawDesc)))
	})
	return file_v1_user_proto_rawDescData
}

var file_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_v1_user_proto_goTypes = []any{
	(*CreateTokenRequest)(nil),  // 0: CreateTokenRequest
	(*TokenReply)(nil),          // 1: TokenReply
	(*GetSubOfToken)(nil),       // 2: GetSubOfToken
	(*SubReply)(nil),            // 3: SubReply
	(*UseTokenRequest)(nil),     // 4: UseTokenRequest
	(*SubscriptionRequest)(nil), // 5: SubscriptionRequest
	(*SubscriptionReply)(nil),   // 6: SubscriptionReply
	(*ActivateRequest)(nil),     // 7: ActivateRequest
	(*ActivateReply)(nil),       // 8: ActivateReply
	(*PeriodRequest)(nil),       // 9: PeriodRequest
	(*ActiveReply)(nil),         // 10: ActiveReply
	(*ActiveSubscriber)(nil),    // 11: ActiveSubscriber
	(*UpdateRequest)(nil),       // 12: UpdateRequest
	(*DeleteRequest)(nil),       // 13: DeleteRequest
	(*empty.Empty)(nil),         // 14: google.protobuf.Empty
}
var file_v1_user_proto_depIdxs = []int32{
	11, // 0: ActiveReply.subscriptions:type_name -> ActiveSubscriber
	5,  // 1: UpdateRequest.subscriber:type_name -> SubscriptionRequest
	5,  // 2: UserService.AddSubscription:input_type -> SubscriptionRequest
	7,  // 3: UserService.ActivateSubscription:input_type -> ActivateRequest
	9,  // 4: UserService.GetActiveSubscriptions:input_type -> PeriodRequest
	12, // 5: UserService.UpdateSubscription:input_type -> UpdateRequest
	13, // 6: UserService.DeleteSubscription:input_type -> DeleteRequest
	0,  // 7: UserService.CreateToken:input_type -> CreateTokenRequest
	2,  // 8: UserService.GetSubscriptionOfToken:input_type -> GetSubOfToken
	4,  // 9: UserService.UseToken:input_type -> UseTokenRequest
	6,  // 10: UserService.AddSubscription:output_type -> SubscriptionReply
	8,  // 11: UserService.ActivateSubscription:output_type -> ActivateReply
	10, // 12: UserService.GetActiveSubscriptions:output_type -> ActiveReply
	14, // 13: UserService.UpdateSubscription:output_type -> google.protobuf.Empty
	14, // 14: UserService.DeleteSubscription:output_type -> google.protobuf.Empty
	1,  // 15: UserService.CreateToken:output_type -> TokenReply
	3,  // 16: UserService.GetSubscriptionOfToken:output_type -> SubReply
	14, // 17: UserService.UseToken:output_type -> google.protobuf.Empty
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_v1_user_proto_init() }
func file_v1_user_proto_init() {
	if File_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_user_proto_rawDesc), len(file_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_user_proto_goTypes,
		DependencyIndexes: file_v1_user_proto_depIdxs,
		MessageInfos:      file_v1_user_proto_msgTypes,
	}.Build()
	File_v1_user_proto = out.File
	file_v1_user_proto_goTypes = nil
	file_v1_user_proto_depIdxs = nil
}
